### ISSUE TITLE
How to use this for hacking 

### ISSUE THREAD

**Issue by xcy7e** [floffel/is_project#1]
Dear floffel the mighty dev,

Thanks for this awesome Software. I c the code not sharp, so I don't know how to hack something with it.

Is it broken? Maybe needs more java?

Haven't seen ya in a while flo'ffel, hope you are well, still on the run and have not been prosecuted yet, you bad badfinger ÷)

Greetings, from far away in time.

**Comment by floffel** [comment]
Hey, cool to see you want to use my software.
It's a prototype and has some bugs, so you would have to work on it before it works for you.
The purpose is to find similarities in names. It was ment for scientific papers, to compare the author names to each other. We could then filter out which names are so similar to other names, that the author might misspelled his:her name in one of the publications.

So, it its purpose is clearly not meant for hacking (as this seems not legal in Germany according to § 202c STGB but I'm no lawyer) :speak_no_evil:

Hope you enjoy it anyway!
Feel free to text me for any questions (check your mails for my contact informations)
